---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории 1
  - Пользователь должен иметь возможность фильтровать товары 2
  - Пользователь должен иметь возможность добавлять товары в корзину 3
non-functional:
  - Пользователь должен иметь возможность просматривать содержимое корзины 1
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре 2
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для
    скорости работы 3
implicit:
  - Сайт должен быть доступен на различных устройствах 1
  - Важно, чтобы сайт мог обрабатывать большое количество трафика 2
  - Сайт нужно протестировать на совместимость с последними версиями браузеров 3
  - Сайт должен иметь мобильную версию 4
  - Сайт должен быть безопасным и защищать данные пользователя 5
